### PR TITLE
Fix java.lang.IllegalStateException: Cannot call sendError() after the response has been committed

### PR DESCRIPTION
**Pull request by stodi1**
The sendError was raising an exception and is seen when sending the response to Chrome browser

### CODE REVIEW

**Comment by isopropylcyanide** [comment]
**Thanks for the contribution**. Can you comment on what is incorrect about not raising an "exception" here?

`sendError` method is supposed to return 403 Unauthorized if the token isn't valid. Why would you want to swallow the exception?

**Comment by stodi1** [comment]
Okay, I think I have missed something. The exception is mandatory when the token is invalid. However, when the token is expired, the ```sendError()``` method will raise the IllegalStateException and will not return the Unauthorized error to some browsers (the error is raised in Chrome and Microsoft edge, Firefox works fine).

**Comment by isopropylcyanide** [comment]
Okay, got it. Haven't reproduced it yet. Would you be willing to submit a PR highlighting the reproduction scenarios?

**Comment by krupalshah** [comment]
@isopropylcyanide I have reproduced the same with an expired auth token. Please merge this PR https://github.com/isopropylcyanide/Jwt-Spring-Security-JPA/pull/43. It fixes the issue by adding a check whether response has already been committed or not.

**Comment by isopropylcyanide** [comment]
Thanks @krupalshah Merged.

**Pull request merged**
